spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://127.0.0.1:18200
      authentication: TOKEN
      application-name: diary
      kv:
        backend: secret
        profiles:
          - local
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 766761247827-viu45ji8m8907uheihp24q3hs5sv3c83.apps.googleusercontent.com
            client-secret: ${GOOGLE_LOCAL_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
app:
  domain:
    http://localhost:5173
  frontend:
    oauth-callback-url: http://localhost:5173/oauth/callback
